name 'app-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures app-cookbook'
long_description 'Installs/Configures app-cookbook'
version '0.1.0'

depends 'tomcat'
depends 'java'